root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = []
  exclude_file = []
  exclude_regex = []
  follow_symlink = false
  delay = 1000 # Milliseconds

[log]
  time = true
  level = "debug"

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
